import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { AlertTriangle, Plus, Eye, CheckCircle, Clock, FileText } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { format } from 'date-fns';
import { it } from 'date-fns/locale';
import { toast } from 'sonner';

export default function Incidents() {
  const navigate = useNavigate();
  const [incidents, setIncidents] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showAddDialog, setShowAddDialog] = useState(false);
  const [selectedIncident, setSelectedIncident] = useState<any>(null);
  const [showDetailDialog, setShowDetailDialog] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editData, setEditData] = useState<any>(null);
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    severity: 'medium',
    category: 'other',
    detected_at: new Date().toISOString().slice(0, 16),
    affected_users_count: '',
    data_compromised: false,
    estimated_impact: 'medium',
    assigned_to: '',
    immediate_actions: ''
  });

  useEffect(() => {
    loadIncidents();
  }, []);

  const loadIncidents = async () => {
    try {
      const { data, error } = await supabase
        .from('security_incidents')
        .select('*')
        .order('detected_at', { ascending: false });

      if (error) throw error;
      setIncidents(data || []);
    } catch (error) {
      console.error('Error loading incidents:', error);
      toast.error('Errore nel caricamento');
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    console.log('🔍 [1] Form submission started');
    console.log('🔍 [2] Form data:', formData);
    
    try {
      // Get organization - use first organization from DB if not in localStorage (DEMO mode)
      let organizationId = null;
      
      const orgData = localStorage.getItem('selectedOrganization');
      if (orgData) {
        const org = JSON.parse(orgData);
        organizationId = org.id;
        console.log('🔍 [3] Organization from localStorage:', organizationId);
      } else {
        console.log('🔍 [3] No organization in localStorage, fetching first org...');
        const { data: orgs, error: orgError } = await supabase
          .from('organization')
          .select('id')
          .limit(1)
          .single();
        
        if (orgError || !orgs) {
          console.error('❌ No organization found:', orgError);
          toast.error('Nessuna organizzazione trovata. Configura prima l\'organizzazione.');
          return;
        }
        
        organizationId = orgs.id;
        console.log('🔍 [3.1] Using first organization:', organizationId);
      }

      const incidentData = {
        organization_id: organizationId,
        incident_id: '', // Will be auto-generated by trigger
        title: formData.title,
        description: formData.description,
        severity: formData.severity,
        category: formData.category,
        detected_at: new Date(formData.detected_at).toISOString(),
        affected_users_count: formData.affected_users_count ? parseInt(formData.affected_users_count) : null,
        data_compromised: formData.data_compromised,
        estimated_impact: formData.estimated_impact,
        assigned_to: formData.assigned_to || null,
        immediate_actions: formData.immediate_actions || null,
        status: 'open',
        reported_at: new Date().toISOString()
      };
      
      console.log('🔍 [4] Incident data to insert:', incidentData);

      const { data, error } = await supabase
        .from('security_incidents')
        .insert([incidentData])
        .select()
        .single();

      if (error) {
        console.error('❌ [5] Supabase error:', error);
        console.error('Error code:', error.code);
        console.error('Error message:', error.message);
        console.error('Error details:', error.details);
        throw error;
      }

      console.log('✅ [6] Incident saved:', data);
      toast.success('⚠️ Incidente registrato!');
      setShowAddDialog(false);
      setFormData({
        title: '',
        description: '',
        severity: 'medium',
        category: 'other',
        detected_at: new Date().toISOString().slice(0, 16),
        affected_users_count: '',
        data_compromised: false,
        estimated_impact: 'medium',
        assigned_to: '',
        immediate_actions: ''
      });
      loadIncidents();
    } catch (error: any) {
      console.error('❌ [ERROR] Exception:', error);
      toast.error('Errore nel salvataggio: ' + (error.message || 'Unknown error'));
    }
  };

  const updateStatus = async (incidentId: string, newStatus: string) => {
    try {
      const updates: any = { status: newStatus };
      
      if (newStatus === 'resolved') {
        updates.resolved_at = new Date().toISOString();
      } else if (newStatus === 'closed') {
        updates.closed_at = new Date().toISOString();
      }

      const { error } = await supabase
        .from('security_incidents')
        .update(updates)
        .eq('id', incidentId);

      if (error) throw error;

      toast.success('Status aggiornato!');
      
      // Update local state if this is the selected incident
      if (selectedIncident?.id === incidentId) {
        setSelectedIncident({ ...selectedIncident, ...updates });
      }
      
      loadIncidents();
    } catch (error) {
      console.error('Error updating status:', error);
      toast.error('Errore aggiornamento');
    }
  };

  const handleSaveDetails = async () => {
    try {
      const { error } = await supabase
        .from('security_incidents')
        .update({
          containment_actions: editData.containment_actions,
          eradication_actions: editData.eradication_actions,
          recovery_actions: editData.recovery_actions,
          root_cause: editData.root_cause,
          lessons_learned: editData.lessons_learned,
          preventive_actions: editData.preventive_actions,
          reported_to_authorities: editData.reported_to_authorities,
          authority_reference: editData.authority_reference,
          reported_to_dpo: editData.reported_to_dpo,
          updated_at: new Date().toISOString()
        })
        .eq('id', selectedIncident.id);

      if (error) throw error;

      toast.success('Incidente aggiornato!');
      setSelectedIncident({ ...selectedIncident, ...editData });
      setIsEditing(false);
      loadIncidents();
    } catch (error: any) {
      console.error('Update error:', error);
      toast.error('Errore aggiornamento: ' + error.message);
    }
  };

  const exportIncidentReport = (incident: any) => {
    const reportContent = `
INCIDENT REPORT
================

ID: ${incident.incident_id}
Title: ${incident.title}
Severity: ${incident.severity.toUpperCase()}
Category: ${getCategoryLabel(incident.category)}
Status: ${getStatusLabel(incident.status)}

DESCRIPTION:
${incident.description}

IMPACT:
- Estimated Impact: ${incident.estimated_impact || 'N/A'}
- Affected Users: ${incident.affected_users_count || 0}
- Data Compromised: ${incident.data_compromised ? 'Yes' : 'No'}

TIMELINE:
- Detected: ${format(new Date(incident.detected_at), 'dd/MM/yyyy HH:mm', { locale: it })}
- Reported: ${format(new Date(incident.reported_at), 'dd/MM/yyyy HH:mm', { locale: it })}
${incident.resolved_at ? `- Resolved: ${format(new Date(incident.resolved_at), 'dd/MM/yyyy HH:mm', { locale: it })}` : ''}
${incident.closed_at ? `- Closed: ${format(new Date(incident.closed_at), 'dd/MM/yyyy HH:mm', { locale: it })}` : ''}

RESPONSE ACTIONS:
==================

1. IMMEDIATE ACTIONS:
${incident.immediate_actions || 'N/A'}

2. CONTAINMENT:
${incident.containment_actions || 'N/A'}

3. ERADICATION:
${incident.eradication_actions || 'N/A'}

4. RECOVERY:
${incident.recovery_actions || 'N/A'}

ANALYSIS:
=========

ROOT CAUSE:
${incident.root_cause || 'TBD'}

LESSONS LEARNED:
${incident.lessons_learned || 'TBD'}

PREVENTIVE ACTIONS:
${incident.preventive_actions || 'TBD'}

REPORTING:
==========
- Reported to Authorities: ${incident.reported_to_authorities ? 'Yes' : 'No'}
${incident.authority_reference ? `- Authority Reference: ${incident.authority_reference}` : ''}
- Reported to DPO: ${incident.reported_to_dpo ? 'Yes' : 'No'}

Assigned to: ${incident.assigned_to || 'N/A'}
`;

    const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `incident_report_${incident.incident_id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
    
    toast.success('Report esportato!');
  };

  const getNextActions = (status: string) => {
    switch (status) {
      case 'open':
        return [
          { label: '🔍 Inizia Investigazione', status: 'investigating', variant: 'default' as const }
        ];
      case 'investigating':
        return [
          { label: '🛡️ Contieni Incidente', status: 'contained', variant: 'default' as const },
          { label: '✅ Risolvi Direttamente', status: 'resolved', variant: 'secondary' as const }
        ];
      case 'contained':
        return [
          { label: '✅ Segna come Risolto', status: 'resolved', variant: 'default' as const }
        ];
      case 'resolved':
        return [
          { label: '🔒 Chiudi Incidente', status: 'closed', variant: 'default' as const }
        ];
      default:
        return [];
    }
  };

  const getSeverityColor = (severity: string) => {
    const colors: Record<string, string> = {
      critical: 'bg-red-500',
      high: 'bg-orange-500',
      medium: 'bg-yellow-500',
      low: 'bg-blue-500'
    };
    return colors[severity] || 'bg-gray-500';
  };

  const getStatusColor = (status: string) => {
    const colors: Record<string, any> = {
      open: 'destructive',
      investigating: 'secondary',
      contained: 'secondary',
      resolved: 'default',
      closed: 'outline'
    };
    return colors[status] || 'outline';
  };

  const getStatusLabel = (status: string) => {
    const labels: Record<string, string> = {
      open: 'Aperto',
      investigating: 'In Analisi',
      contained: 'Contenuto',
      resolved: 'Risolto',
      closed: 'Chiuso'
    };
    return labels[status] || status;
  };

  const getCategoryLabel = (category: string) => {
    const labels: Record<string, string> = {
      data_breach: 'Data Breach',
      malware: 'Malware',
      unauthorized_access: 'Accesso Non Autorizzato',
      ddos: 'DDoS',
      phishing: 'Phishing',
      physical: 'Sicurezza Fisica',
      other: 'Altro'
    };
    return labels[category] || category;
  };

  // Calculate stats
  const stats = {
    total: incidents.length,
    open: incidents.filter(i => i.status === 'open').length,
    critical: incidents.filter(i => i.severity === 'critical' && i.status !== 'closed').length,
    resolved: incidents.filter(i => i.status === 'resolved' || i.status === 'closed').length
  };

  return (
    <div className="space-y-6 p-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold flex items-center gap-2">
            <AlertTriangle className="h-8 w-8 text-orange-500" />
            Gestione Incidenti Sicurezza
          </h1>
          <p className="text-muted-foreground mt-1">
            Registro incidenti per compliance ISO 27001 (Clause 5.24-5.28)
          </p>
        </div>
        <Dialog open={showAddDialog} onOpenChange={setShowAddDialog}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="h-4 w-4 mr-2" />
              Registra Incidente
            </Button>
          </DialogTrigger>
          <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>Nuovo Incidente di Sicurezza</DialogTitle>
              <DialogDescription>
                Registra un incidente di sicurezza delle informazioni
              </DialogDescription>
            </DialogHeader>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="space-y-2">
                <Label>Titolo Incidente *</Label>
                <Input
                  required
                  value={formData.title}
                  onChange={(e) => setFormData({...formData, title: e.target.value})}
                  placeholder="es. Tentativo accesso non autorizzato al server"
                />
              </div>

              <div className="space-y-2">
                <Label>Descrizione *</Label>
                <Textarea
                  required
                  value={formData.description}
                  onChange={(e) => setFormData({...formData, description: e.target.value})}
                  placeholder="Descrivi l'incidente in dettaglio..."
                  rows={4}
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Severità *</Label>
                  <Select 
                    value={formData.severity}
                    onValueChange={(value) => setFormData({...formData, severity: value})}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="critical">🔴 Critica</SelectItem>
                      <SelectItem value="high">🟠 Alta</SelectItem>
                      <SelectItem value="medium">🟡 Media</SelectItem>
                      <SelectItem value="low">🔵 Bassa</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label>Categoria *</Label>
                  <Select 
                    value={formData.category}
                    onValueChange={(value) => setFormData({...formData, category: value})}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="data_breach">Data Breach</SelectItem>
                      <SelectItem value="malware">Malware</SelectItem>
                      <SelectItem value="unauthorized_access">Accesso Non Autorizzato</SelectItem>
                      <SelectItem value="ddos">DDoS</SelectItem>
                      <SelectItem value="phishing">Phishing</SelectItem>
                      <SelectItem value="physical">Sicurezza Fisica</SelectItem>
                      <SelectItem value="other">Altro</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Data/Ora Rilevamento *</Label>
                  <Input
                    type="datetime-local"
                    required
                    value={formData.detected_at}
                    onChange={(e) => setFormData({...formData, detected_at: e.target.value})}
                  />
                </div>

                <div className="space-y-2">
                  <Label>Impatto Stimato</Label>
                  <Select 
                    value={formData.estimated_impact}
                    onValueChange={(value) => setFormData({...formData, estimated_impact: value})}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="critical">Critico</SelectItem>
                      <SelectItem value="high">Alto</SelectItem>
                      <SelectItem value="medium">Medio</SelectItem>
                      <SelectItem value="low">Basso</SelectItem>
                      <SelectItem value="minimal">Minimo</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Utenti Coinvolti (n.)</Label>
                  <Input
                    type="number"
                    value={formData.affected_users_count}
                    onChange={(e) => setFormData({...formData, affected_users_count: e.target.value})}
                    placeholder="0"
                  />
                </div>

                <div className="space-y-2">
                  <Label>Dati Compromessi</Label>
                  <Select 
                    value={formData.data_compromised ? 'true' : 'false'}
                    onValueChange={(value) => setFormData({...formData, data_compromised: value === 'true'})}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="false">No</SelectItem>
                      <SelectItem value="true">Sì</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="space-y-2">
                <Label>Assegnato a</Label>
                <Input
                  value={formData.assigned_to}
                  onChange={(e) => setFormData({...formData, assigned_to: e.target.value})}
                  placeholder="Nome responsabile"
                />
              </div>

              <div className="space-y-2">
                <Label>Azioni Immediate</Label>
                <Textarea
                  value={formData.immediate_actions}
                  onChange={(e) => setFormData({...formData, immediate_actions: e.target.value})}
                  placeholder="Azioni intraprese immediatamente..."
                  rows={3}
                />
              </div>

              <div className="flex justify-end gap-2">
                <Button type="button" variant="outline" onClick={() => setShowAddDialog(false)}>
                  Annulla
                </Button>
                <Button type="submit">
                  Registra Incidente
                </Button>
              </div>
            </form>
          </DialogContent>
        </Dialog>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-4 gap-4">
        <Card>
          <CardHeader className="pb-2">
            <CardDescription>Totali</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold">{stats.total}</div>
          </CardContent>
        </Card>
        <Card className="border-red-200">
          <CardHeader className="pb-2">
            <CardDescription>Aperti</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-red-600">{stats.open}</div>
          </CardContent>
        </Card>
        <Card className="border-orange-200">
          <CardHeader className="pb-2">
            <CardDescription>Critici Attivi</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-orange-600">{stats.critical}</div>
          </CardContent>
        </Card>
        <Card className="border-green-200">
          <CardHeader className="pb-2">
            <CardDescription>Risolti</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-green-600">{stats.resolved}</div>
          </CardContent>
        </Card>
      </div>

      {/* Incidents Table */}
      <Card>
        <CardHeader>
          <CardTitle>Registro Incidenti</CardTitle>
          <CardDescription>
            Storico completo incidenti di sicurezza
          </CardDescription>
        </CardHeader>
        <CardContent>
          {loading ? (
            <div className="text-center py-8">Caricamento...</div>
          ) : incidents.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              Nessun incidente registrato 🎉
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>ID</TableHead>
                  <TableHead>Incidente</TableHead>
                  <TableHead>Severità</TableHead>
                  <TableHead>Categoria</TableHead>
                  <TableHead>Rilevato</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Azioni</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {incidents.map((incident) => (
                  <TableRow key={incident.id}>
                    <TableCell className="font-mono text-sm">
                      {incident.incident_id}
                    </TableCell>
                    <TableCell>
                      <div className="max-w-xs">
                        <div className="font-medium">{incident.title}</div>
                        {incident.assigned_to && (
                          <div className="text-xs text-muted-foreground">
                            Ass.: {incident.assigned_to}
                          </div>
                        )}
                      </div>
                    </TableCell>
                    <TableCell>
                      <Badge className={getSeverityColor(incident.severity)}>
                        {incident.severity.toUpperCase()}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      <span className="text-sm">{getCategoryLabel(incident.category)}</span>
                    </TableCell>
                    <TableCell>
                      {format(new Date(incident.detected_at), 'dd/MM/yyyy HH:mm', { locale: it })}
                    </TableCell>
                    <TableCell>
                      <Badge variant={getStatusColor(incident.status)}>
                        {getStatusLabel(incident.status)}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      <div className="flex gap-1">
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => {
                            setSelectedIncident(incident);
                            setShowDetailDialog(true);
                          }}
                        >
                          <Eye className="h-4 w-4" />
                        </Button>
                        {incident.status === 'open' && (
                          <Button
                            size="sm"
                            variant="ghost"
                            onClick={() => updateStatus(incident.id, 'investigating')}
                          >
                            <Clock className="h-4 w-4" />
                          </Button>
                        )}
                        {(incident.status === 'investigating' || incident.status === 'contained') && (
                          <Button
                            size="sm"
                            variant="ghost"
                            onClick={() => updateStatus(incident.id, 'resolved')}
                          >
                            <CheckCircle className="h-4 w-4" />
                          </Button>
                        )}
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Detail Dialog */}
      <Dialog open={showDetailDialog} onOpenChange={(open) => {
        setShowDetailDialog(open);
        if (!open) {
          setIsEditing(false);
          setEditData(null);
        }
      }}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <div className="flex justify-between items-start gap-4">
              <DialogTitle className="flex items-center gap-2">
                <AlertTriangle className="h-5 w-5" />
                {selectedIncident?.incident_id} - {selectedIncident?.title}
              </DialogTitle>
              <div className="flex gap-2">
                <Button 
                  size="sm" 
                  variant="outline"
                  onClick={() => selectedIncident && exportIncidentReport(selectedIncident)}
                >
                  📥 Export
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => selectedIncident && navigate(
                    `/non-conformity/new?source=incident&sourceId=${selectedIncident.id}&title=${encodeURIComponent('NC da Incident: ' + (selectedIncident.title || ''))}&description=${encodeURIComponent(selectedIncident.description || '')}&severity=${selectedIncident.severity === 'critical' || selectedIncident.severity === 'high' ? 'major' : 'minor'}`
                  )}
                >
                  <AlertTriangle className="h-4 w-4 mr-1" />
                  Crea NC
                </Button>
                {!isEditing && selectedIncident?.status !== 'closed' && (
                  <Button size="sm" variant="outline" onClick={() => {
                    setIsEditing(true);
                    setEditData(selectedIncident);
                  }}>
                    ✏️ Modifica
                  </Button>
                )}
                {isEditing && (
                  <>
                    <Button size="sm" variant="outline" onClick={() => {
                      setIsEditing(false);
                      setEditData(null);
                    }}>
                      Annulla
                    </Button>
                    <Button size="sm" onClick={handleSaveDetails}>
                      💾 Salva
                    </Button>
                  </>
                )}
              </div>
            </div>
          </DialogHeader>

          {selectedIncident && (
            <div className="space-y-6">
              {/* Status & Actions */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-base">Status e Azioni</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex items-center justify-between flex-wrap gap-4">
                    <div>
                      <Label className="text-xs text-muted-foreground">Status Corrente</Label>
                      <div className="mt-1">
                        <Badge variant={getStatusColor(selectedIncident.status)} className="text-base">
                          {getStatusLabel(selectedIncident.status)}
                        </Badge>
                      </div>
                    </div>
                    {selectedIncident.status !== 'closed' && (
                      <div className="flex gap-2 flex-wrap">
                        {getNextActions(selectedIncident.status).map(action => (
                          <Button
                            key={action.status}
                            variant={action.variant}
                            size="sm"
                            onClick={() => updateStatus(selectedIncident.id, action.status)}
                          >
                            {action.label}
                          </Button>
                        ))}
                      </div>
                    )}
                  </div>
                </CardContent>
              </Card>

              {/* Timeline */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-base">Timeline</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    <div className="flex gap-3">
                      <div className="w-2 h-2 rounded-full bg-red-500 mt-2 flex-shrink-0"></div>
                      <div className="flex-1">
                        <p className="text-sm font-medium">Incidente Rilevato</p>
                        <p className="text-xs text-muted-foreground">
                          {format(new Date(selectedIncident.detected_at), 'dd/MM/yyyy HH:mm', { locale: it })}
                        </p>
                      </div>
                    </div>

                    <div className="flex gap-3">
                      <div className="w-2 h-2 rounded-full bg-blue-500 mt-2 flex-shrink-0"></div>
                      <div className="flex-1">
                        <p className="text-sm font-medium">Incidente Registrato</p>
                        <p className="text-xs text-muted-foreground">
                          {format(new Date(selectedIncident.reported_at), 'dd/MM/yyyy HH:mm', { locale: it })}
                        </p>
                      </div>
                    </div>

                    {selectedIncident.resolved_at && (
                      <div className="flex gap-3">
                        <div className="w-2 h-2 rounded-full bg-green-500 mt-2 flex-shrink-0"></div>
                        <div className="flex-1">
                          <p className="text-sm font-medium">Incidente Risolto</p>
                          <p className="text-xs text-muted-foreground">
                            {format(new Date(selectedIncident.resolved_at), 'dd/MM/yyyy HH:mm', { locale: it })}
                          </p>
                        </div>
                      </div>
                    )}

                    {selectedIncident.closed_at && (
                      <div className="flex gap-3">
                        <div className="w-2 h-2 rounded-full bg-gray-500 mt-2 flex-shrink-0"></div>
                        <div className="flex-1">
                          <p className="text-sm font-medium">Incidente Chiuso</p>
                          <p className="text-xs text-muted-foreground">
                            {format(new Date(selectedIncident.closed_at), 'dd/MM/yyyy HH:mm', { locale: it })}
                          </p>
                        </div>
                      </div>
                    )}
                  </div>
                </CardContent>
              </Card>

              {/* Basic Info */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-base">Informazioni Base</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label className="text-xs text-muted-foreground">Severità</Label>
                      <div className="mt-1">
                        <Badge className={getSeverityColor(selectedIncident.severity)}>
                          {selectedIncident.severity.toUpperCase()}
                        </Badge>
                      </div>
                    </div>
                    <div>
                      <Label className="text-xs text-muted-foreground">Categoria</Label>
                      <p className="text-sm mt-1">{getCategoryLabel(selectedIncident.category)}</p>
                    </div>
                  </div>

                  <div>
                    <Label className="text-xs text-muted-foreground">Descrizione</Label>
                    <p className="text-sm mt-1 whitespace-pre-wrap">{selectedIncident.description}</p>
                  </div>

                  {selectedIncident.assigned_to && (
                    <div>
                      <Label className="text-xs text-muted-foreground">Assegnato a</Label>
                      <p className="text-sm mt-1">{selectedIncident.assigned_to}</p>
                    </div>
                  )}
                </CardContent>
              </Card>

              {/* Impact */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-base">Impatto</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  <div className="grid grid-cols-3 gap-4">
                    <div>
                      <Label className="text-xs text-muted-foreground">Impatto Stimato</Label>
                      <Badge variant="outline" className="mt-1">
                        {selectedIncident.estimated_impact || 'N/A'}
                      </Badge>
                    </div>
                    <div>
                      <Label className="text-xs text-muted-foreground">Utenti Coinvolti</Label>
                      <p className="text-sm mt-1">{selectedIncident.affected_users_count || 0}</p>
                    </div>
                    <div>
                      <Label className="text-xs text-muted-foreground">Dati Compromessi</Label>
                      <Badge variant={selectedIncident.data_compromised ? 'destructive' : 'outline'} className="mt-1">
                        {selectedIncident.data_compromised ? '⚠️ Sì' : '✅ No'}
                      </Badge>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Response Actions */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-base">Risposta all'Incidente</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  {/* Immediate Actions */}
                  <div>
                    <Label className="text-xs text-muted-foreground">1️⃣ Azioni Immediate</Label>
                    {isEditing ? (
                      <Textarea
                        value={editData?.immediate_actions || ''}
                        onChange={(e) => setEditData({...editData, immediate_actions: e.target.value})}
                        placeholder="Azioni intraprese subito dopo la scoperta..."
                        rows={3}
                        className="mt-1"
                      />
                    ) : (
                      <p className="text-sm mt-1 whitespace-pre-wrap">
                        {selectedIncident.immediate_actions || '—'}
                      </p>
                    )}
                  </div>

                  {/* Containment */}
                  <div>
                    <Label className="text-xs text-muted-foreground">2️⃣ Contenimento</Label>
                    {isEditing ? (
                      <Textarea
                        value={editData?.containment_actions || ''}
                        onChange={(e) => setEditData({...editData, containment_actions: e.target.value})}
                        placeholder="Come è stato contenuto l'incidente..."
                        rows={3}
                        className="mt-1"
                      />
                    ) : (
                      <p className="text-sm mt-1 whitespace-pre-wrap">
                        {selectedIncident.containment_actions || '—'}
                      </p>
                    )}
                  </div>

                  {/* Eradication */}
                  <div>
                    <Label className="text-xs text-muted-foreground">3️⃣ Eradicazione</Label>
                    {isEditing ? (
                      <Textarea
                        value={editData?.eradication_actions || ''}
                        onChange={(e) => setEditData({...editData, eradication_actions: e.target.value})}
                        placeholder="Come è stata eliminata la causa..."
                        rows={3}
                        className="mt-1"
                      />
                    ) : (
                      <p className="text-sm mt-1 whitespace-pre-wrap">
                        {selectedIncident.eradication_actions || '—'}
                      </p>
                    )}
                  </div>

                  {/* Recovery */}
                  <div>
                    <Label className="text-xs text-muted-foreground">4️⃣ Recupero</Label>
                    {isEditing ? (
                      <Textarea
                        value={editData?.recovery_actions || ''}
                        onChange={(e) => setEditData({...editData, recovery_actions: e.target.value})}
                        placeholder="Come è stato ripristinato il servizio..."
                        rows={3}
                        className="mt-1"
                      />
                    ) : (
                      <p className="text-sm mt-1 whitespace-pre-wrap">
                        {selectedIncident.recovery_actions || '—'}
                      </p>
                    )}
                  </div>
                </CardContent>
              </Card>

              {/* Analysis */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-base">Analisi Post-Incidente</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  {/* Root Cause */}
                  <div>
                    <Label className="text-xs text-muted-foreground">🔍 Root Cause (Causa Radice)</Label>
                    {isEditing ? (
                      <Textarea
                        value={editData?.root_cause || ''}
                        onChange={(e) => setEditData({...editData, root_cause: e.target.value})}
                        placeholder="Quale è stata la causa principale dell'incidente..."
                        rows={3}
                        className="mt-1"
                      />
                    ) : (
                      <p className="text-sm mt-1 whitespace-pre-wrap">
                        {selectedIncident.root_cause || '—'}
                      </p>
                    )}
                  </div>

                  {/* Lessons Learned */}
                  <div>
                    <Label className="text-xs text-muted-foreground">💡 Lessons Learned (Lezioni Apprese)</Label>
                    {isEditing ? (
                      <Textarea
                        value={editData?.lessons_learned || ''}
                        onChange={(e) => setEditData({...editData, lessons_learned: e.target.value})}
                        placeholder="Cosa abbiamo imparato da questo incidente..."
                        rows={3}
                        className="mt-1"
                      />
                    ) : (
                      <p className="text-sm mt-1 whitespace-pre-wrap">
                        {selectedIncident.lessons_learned || '—'}
                      </p>
                    )}
                  </div>

                  {/* Preventive Actions */}
                  <div>
                    <Label className="text-xs text-muted-foreground">🛡️ Azioni Preventive</Label>
                    {isEditing ? (
                      <Textarea
                        value={editData?.preventive_actions || ''}
                        onChange={(e) => setEditData({...editData, preventive_actions: e.target.value})}
                        placeholder="Cosa faremo per prevenire incidenti simili..."
                        rows={3}
                        className="mt-1"
                      />
                    ) : (
                      <p className="text-sm mt-1 whitespace-pre-wrap">
                        {selectedIncident.preventive_actions || '—'}
                      </p>
                    )}
                  </div>
                </CardContent>
              </Card>

              {/* Reporting */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-base">Segnalazioni</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  {isEditing ? (
                    <>
                      <div className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          id="reported_authorities"
                          checked={editData?.reported_to_authorities || false}
                          onChange={(e) => setEditData({...editData, reported_to_authorities: e.target.checked})}
                          className="rounded"
                        />
                        <Label htmlFor="reported_authorities" className="text-sm">
                          🏛️ Segnalato alle Autorità
                        </Label>
                      </div>
                      {editData?.reported_to_authorities && (
                        <Input
                          placeholder="Riferimento autorità"
                          value={editData?.authority_reference || ''}
                          onChange={(e) => setEditData({...editData, authority_reference: e.target.value})}
                          className="ml-6"
                        />
                      )}
                      <div className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          id="reported_dpo"
                          checked={editData?.reported_to_dpo || false}
                          onChange={(e) => setEditData({...editData, reported_to_dpo: e.target.checked})}
                          className="rounded"
                        />
                        <Label htmlFor="reported_dpo" className="text-sm">
                          👤 Segnalato al DPO
                        </Label>
                      </div>
                    </>
                  ) : (
                    <>
                      {selectedIncident.reported_to_authorities && (
                        <div className="flex items-center gap-2">
                          <Badge>🏛️ Segnalato alle Autorità</Badge>
                          {selectedIncident.authority_reference && (
                            <span className="text-sm text-muted-foreground">
                              Rif: {selectedIncident.authority_reference}
                            </span>
                          )}
                        </div>
                      )}
                      {selectedIncident.reported_to_dpo && (
                        <Badge>👤 Segnalato al DPO</Badge>
                      )}
                      {!selectedIncident.reported_to_authorities && !selectedIncident.reported_to_dpo && (
                        <p className="text-sm text-muted-foreground">Nessuna segnalazione effettuata</p>
                      )}
                    </>
                  )}
                </CardContent>
              </Card>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
